pipelines:
- name: sleep
  steps:
    - name: sleep-5
      type: Bash
      execution:
        onExecute:
        - sleep 5
    - name: sleep-10
      type: Bash
      execution:
        onExecute:
        - sleep 10
