pipelines:
- name: sleep
  steps:
    - name: sleep_5
      type: Bash
      execution:
        onExecute:
        - sleep 5
    - name: sleep_10_minutes
      type: Bash
      execution:
        onExecute:
        - sleep 600
    
